[project]
name = "transformers-sae"
requires-python = ">=3.12,<3.14"
dependencies = [
    "accelerate>=1.12.0",
    "bitarray>=3.8.0",
    "cloudpickle>=3.1.2",
    "datasets>=4.4.2",
    "ml-dtypes>=0.5.4",
    "sae-lens>=6.37.6",
    "safetensors>=0.7.0",
    "torch>=2.11",
    "torchvision>=0.26",
    "transformers>=4.57.3",
    "zarr>=3.1.5",
]
version = "0.0.0"

[project.optional-dependencies]
cuda = ["torch", "torchvision"]
cuda126 = ["torch", "torchvision"]
cuda128 = ["torch", "torchvision"]
cuda130 = ["torch", "torchvision"]
cpu = ["torch", "torchvision"]
xpu = ["torch", "torchvision", "triton-xpu"]
rocm = ["torch", "torchvision", "triton-rocm"]

[tool.setuptools]
packages = [
    "transformers_sae",
    "transformers_sae.training_step",
    "transformers_sae.benchmark",
]

[dependency-groups]
dev = [
    "jurigged>=0.6.1",
    "line-profiler>=5.0.1",
    "ruff>=0.14.10",
    "huggingface_hub>=1.10.2",
    "ipdb>=0.13.13",
    "pdbpp>=0.12.1",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.1",
    "matplotlib>=3.10.8",
    "scipy>=1.17.0",
    "tabulate>=0.10.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu126", extra = "cuda126" },
    { index = "pytorch-cu128", extra = "cuda128" },
    { index = "pytorch-cu128", extra = "cuda" },
    { index = "pytorch-cu130", extra = "cuda130" },
    { index = "pytorch-xpu", extra = "xpu" },
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pytorch-cpu", extra = "cpu" },
]
torchvision = [
    { index = "pytorch-cu126", extra = "cuda126" },
    { index = "pytorch-cu128", extra = "cuda128" },
    { index = "pytorch-cu128", extra = "cuda" },
    { index = "pytorch-cu130", extra = "cuda130" },
    { index = "pytorch-xpu", extra = "xpu" },
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pytorch-cpu", extra = "cpu" },
]
triton-xpu = [{ index = "pytorch-xpu" }]
triton-rocm = [{ index = "pytorch-rocm" }]

[tool.uv]
conflicts = [
    [
        { extra = "cuda" },
        { extra = "cuda126" },
        { extra = "cuda128" },
        { extra = "cuda130" },
        { extra = "cpu" },
        { extra = "xpu" },
        { extra = "rocm" },
    ],
]

[tool.ty]
rules = { all = "warn", missing-argument = "error", missing-override-decorator = "ignore" }

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "E703",
] # allow trailing semi-colons in notebooks to suppress output
